project:
  type: reporting-website

reporting-website: 
  title: "Demo Website"
  navbar: 
    left:
      - text: Home
        file: index.qmd
 
  sidebar: 
    type: docked
    contents: reports

format:
  html: 
    toc: false 
    author: "Kevin Reuning"
